version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: .
    container_name: mern-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern_app
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend   # 👈 tells Docker to look inside client/
      dockerfile: Dockerfile
    container_name: mern-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
